version: "3.4"

services:
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"

    environment:
      SA_PASSWORD: "TddDb123"
      ACCEPT_EULA: "Y"
  
volumes:
  db:
    driver: local
